"""add job source_publisher for apply link labelling

Revision ID: 0b3bfd55c456
Revises: 5c61587522d0
Create Date: 2026-08-30 15:47:01.498839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b3bfd55c456'
down_revision: Union[str, None] = '5c61587522d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_publisher', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source_publisher')
    # ### end Alembic commands ###
