"""add user_jobs: which user added which pasted job

Revision ID: 524a1fa660af
Revises: 1dc7b070c23d
Create Date: 2026-09-07 16:13:24.937944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '524a1fa660af'
down_revision: Union[str, None] = '1dc7b070c23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_user_jobs_added_at'), 'user_jobs', ['added_at'], unique=False)
    op.create_index(op.f('ix_user_jobs_job_id'), 'user_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_user_jobs_user_id'), 'user_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_jobs_user_id'), table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_job_id'), table_name='user_jobs')
    op.drop_index(op.f('ix_user_jobs_added_at'), table_name='user_jobs')
    op.drop_table('user_jobs')
    # ### end Alembic commands ###
