"""widen job external_id for jsearch search-v2 ids

Revision ID: 5c61587522d0
Revises: 9ea172d29d8f
Create Date: 2026-08-30 15:40:02.291052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c61587522d0'
down_revision: Union[str, None] = '9ea172d29d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=768),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'external_id',
               existing_type=sa.String(length=768),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
