"""add application events and reminder tracking

Revision ID: eeedd0605f75
Revises: 9cfa33f125b2
Create Date: 2026-08-30 20:01:14.735282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'eeedd0605f75'
down_revision: Union[str, None] = '9cfa33f125b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: application_status is an existing Postgres enum type, so the columns
    # below reference it with create_type=False. Plain sa.Enum would emit another
    # CREATE TYPE and fail with DuplicateObject.
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', postgresql.ENUM('applied', 'online_assessment', 'interview', 'offer', 'rejected', 'withdrawn', name='application_status', create_type=False), nullable=True),
    sa.Column('to_status', postgresql.ENUM('applied', 'online_assessment', 'interview', 'offer', 'rejected', 'withdrawn', name='application_status', create_type=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_changed_at'), 'application_events', ['changed_at'], unique=False)
    op.add_column('applications', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'last_reminder_at')
    op.drop_index(op.f('ix_application_events_changed_at'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    # ### end Alembic commands ###
